sudo: required
services:
  - docker
before_install:
  - docker build -t testme -f ./client/Dockerfile.dev ./client
script:
  - docker run testme npm run testCI
after_success:
  - docker build -t pragya5833/clientprod ./client
  - docker build -t pragya5833/nginxprod ./nginx
  - docker build -t pragya5833/workerprod  ./worker
  - docker build -t pragya5833/serverprod ./server
  #login to docker cli
  - docker login -u "Docker_Id" -p "$Docker_password" docker.io
  # - echo "$Docker_password" | docker login -u "$Docker_Id" --password-stdin
  #take images and push to dockerhub
  - docker push pragya5833/clientprod:1.0
  - docker push pragya5833/nginxprod:1.0
  - docker push pragya5833/workerprod:1.0
  - docker push pragya5833/serverprod:1.0