sudo: required
services:
  - docker
before_install:
  - docker build -t testme -f ./client/Dockerfile.dev ./client
script:
  - docker run testme npm run testCI
after_success:
  - docker build -t clientprod ./client
  - docker build -t nginxprod ./nginx
  - docker build -t workerprod  ./worker
  - docker build -t serverprod ./server
  #login to docker cli
  - docker login -u "Docker_Id" -p "$Docker_password" docker.io
  # - echo "$Docker_password" | docker login -u "$Docker_Id" --password-stdin
  #take images and push to dockerhub
  - docker push clientprod
  - docker push nginxprod
  - docker push workerprod
  - docker push serverprod