sudo: required
services:
  - docker
before_install:
  - docker build -t testme -f ./client/Dockerfile.dev ./client
script:
  - docker run testme npm run testCI
after_success:
  - docker build -t pragya5833/clientprod:latest ./client
  - docker build -t pragya5833/nginxprod:latest ./nginx
  - docker build -t pragya5833/workerprod:latest ./worker
  - docker build -t pragya5833/serverprod:latest ./server
  #login to docker cli
  #- docker login -u "Docker_Id" -p "$Docker_password" docker.io
  - echo "$Docker_password" | docker login -u "$Docker_Id" --password-stdin
  #take images and push to dockerhub
  - docker push pragya5833/clientprod:latest
  - docker push pragya5833/nginxprod:latest
  - docker push pragya5833/workerprod:latest
  - docker push pragya5833/serverprod:latest
  deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: Multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-554284713240
    bucket_path: docker-multi
    0n:
     branch: master
    access_key_id: $AWS_Access_key
    secret_access_key:
      secure: $AWS_SECRET_KEY